
version: '3.1'


volumes:
  pg_db: {}
  pg_backup: { }


version: '3.1'

volumes:
  mysql_db: {}
  mysql_backup: { }



services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - mysql_db:/var/lib/mysql
      - mysql_backup:/backup

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080