HOSTNAME='1csrv06'
DOMAIN='consalte.ru'
IP='192.168.204.51'
SYS_DISK='/dev/sda1'
PASS='testtest'

Vagrant.configure("2") do |config|
  config.vm.provider :hyperv do |hv|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant"
    hv.vmname = "postgresql_1c"
    hv.cpus = 10
    hv.memory = 32768
    hv.enable_checkpoints = true
    hv.linked_clone = true
    hv.auto_start_action = "StartIfRunning"
    hv.auto_stop_action = "Save"
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "Europe/Moscow" > /etc/timezone
    ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
    echo "$HOSTNAME.$DOMAIN" > /etc/hostname
    hostname $HOSTNAME.$DOMAIN
    echo "$IP $HOSTNAME $HOSTNAME.$DOMAIN" >> /etc/hosts
    setenforce 0
    sed -i 's/SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
    systemctl stop firewalld
    systemctl disable firewalld
    rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    yum update -y
    yum install -y htop hdparm
    localedef -i ru_RU -f UTF-8 ru_RU.UTF-8
    localectl set-locale LANG=ru_RU.utf8
    hdparm -Tt $SYS_DISK > /test.disk.result
    sleep 60
    useradd -m -s /bin/bash itadmin
    echo 'itadmin:Lbvtnhf7373' | chpasswd
    echo 'itadmin   ALL=NOPASSWD: ALL' >> /etc/sudoers
    rpm -i https://repo.postgrespro.ru/pg1c-14/keys/centos.rpm
    yum makecache
    yum install -y postgrespro-1c-14
    /opt/pgpro/1c-14/bin/pg-setup initdb --locale=ru_RU.UTF8
    /opt/pgpro/1c-14/bin/pg-setup service --now enable
    echo "PATH=/usr/local/sbin:/usr/sbin:/usr/bin/:/opt/pgpro/1c-14/bin/:/root/bin" > /etc/environment
    sudo -u postgres /opt/pgpro/1c-14/bin/psql -U postgres -c "alter user postgres with password '$PASS';"
    mkdir /var/lib/pgsql_stats_tmp
    chown postgres:postgres /var/lib/pgsql_stats_tmp
    echo "tmpfs /var/lib/pgsql_stats_tmp tmpfs size=512M,uid=postgres,gid=postgres 0 0" >> /etc/fstab
    mount /var/lib/pgsql_stats_tmp
    echo "stats_temp_directory = '/var/lib/pgsql_stats_tmp'" >> /var/lib/pgpro/1c-14/data/postgresql.conf
    echo "listen_addresses = '*' " >> /var/lib/pgpro/1c-14/data/postgresql.conf
    sudo -u postgres /opt/pgpro/1c-14/bin/psql -U postgres -c "SELECT pg_reload_conf();"
    systemctl restart postgrespro-1c-14.service
  SHELL
end

