
version: '2.2'


networks:
  elastic: {}

volumes:
  certs:
    driver: local
  esdata03:
    driver: local

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es-node01
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ['9200:9200', '9300:9300']
    networks: ['elastic']


  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.1
    restart: always
    depends_on: ['elasticsearch']
    ports: ['5601:5601']
    networks: ['elastic']
